myblog/urls.py
from django.urls import path
from . import views

app_name = 'myblog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post/P<int:pk>', views.PostDetailView.as_view(), name='detail'),
    path('archives/<int:year>/<int:month>', views.ArchivesView.as_view(), name='archives'),
    path('category/C<int:pk>', views.CategoryView.as_view(), name='category'),
    path('tag/T<int:pk>', views.TagView.as_view(), name='tag'),    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from myblog.feeds import AllPostRssFeed
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('all/rss/', AllPostRssFeed(), name='rss'),
    path('search/', include('haystack.urls')),
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
    path('projects/', include("myprojects.urls")),
    path('blog/', include('myblog.urls')),
    path('android_browser/', views.android_browser),
]

myblog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.html import strip_tags
import markdown


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=70)
    body = models.TextField()
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    excerpt = models.CharField(max_length=200, blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('myblog:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-created_time']

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            self.excerpt = strip_tags(md.convert(self.body))[:54]
        super(Post, self).save(*args, **kwargs)

myblog/views.py
import markdown
from django.shortcuts import get_object_or_404
from django.utils.text import slugify
from django.views.generic import ListView, DetailView
from markdown.extensions.toc import TocExtension

from .models import Post, Category, Tag

MONTH_NAME_MAP = {
    1: 'Jan',
    2: 'Feb',
    3: 'Mar',
    4: 'Apr',
    5: 'May',
    6: 'June',
    7: 'July',
    8: 'Aug',
    9: 'Sep',
    10: 'Oct',
    11: 'Nov',
    12: 'Dec'
}


class PostDetailView(DetailView):
    model = Post
    template_name = 'myblog/detail.html'
    context_object_name = 'post'
    queryset = Post.objects.all()

    def get(self, request, *args, **kwargs):
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        post = super(PostDetailView, self).get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify=slugify)
        ])
        post.body = md.convert(post.body)
        post.toc = md.toc
        return post


class IndexView(ListView):
    model = Post
    template_name = 'myblog/index.html'
    context_object_name = 'post_list'
    paginate_by = 5
    title = 'Blog | Jian Yang'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')
        pagination_data = self.pagination_data(paginator, page, is_paginated)
        context.update(pagination_data)
        context.update({
            'title': self.title,
        })
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            return {}

        left = []
        right = []
        left_has_more = False
        right_has_more = False
        first = False
        last = False

        page_number = page.number
        total_pages = paginator.num_pages
        page_range = paginator.page_range

        if page_number != 1:
            left = page_range[(page_number - 3)
                              if (page_number - 3) > 0 else 0:page_number - 1]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        if page_number != total_pages:
            right = page_range[page_number:page_number + 2]
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last
        }
        return data


class ArchivesView(IndexView):
    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        self.title = MONTH_NAME_MAP[month] + ' ' + str(year) + ' | Jian Yang'
        return super(ArchivesView, self).get_queryset().filter(created_time__year=year,
                                                               created_time__month=month)


class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        self.title = cate.name + ' | Jian Yang'
        return super(CategoryView, self).get_queryset().filter(category=cate)


class TagView(IndexView):
    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        self.title = tag.name + ' | Jian Yang'
        return super(TagView, self).get_queryset().filter(tags=tag)

templates/myblog/base.html
<head>
    <style>
        span.highlighted {
            color: red;
        }
    </style>
</head>

{% extends 'basic/base.html' %}
{% load myblog_tags %}
{% block title %}
    Blog | Jian Yang
{% endblock title%}
{% block main-body %}
    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-8">
                    {% block main %}
                    {% endblock main %}
                </main>
                <aside class="col-md-4">
                    {% block toc %}
                    {% endblock toc %}
                    <div class="widget widget-recent-posts">
                        <h3 class="widget-title">Latest</h3>
                        {% get_recent_posts as recent_post_list %}
                        <ul>
                            {% for post in recent_post_list %}
                            <li>
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </li>
                            {% empty %}
                            No post!
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="widget widget-archives">
                        <h3 class="widget-title">Archives</h3>
                        {% archives as date_list %}
                        <ul>
                            {% for a_date in date_list %}
                            <li>
                                <a href="{% url 'myblog:archives' a_date.year a_date.month %}">{{ a_date|date:'F' }}, {{ a_date.year }}</a>
                            </li>
                            {% empty %}
                            No archive!
                            {% endfor %}
                        </ul>
                    </div>

                    <div class="widget widget-category">
                        <h3 class="widget-title">Categories</h3>
                        {% get_categories as category_list %}
                        <ul>
                            {% for category in category_list %}
                            <li>
                                    <a href="{% url 'myblog:category' category.pk %}">{{ category.name }}<span class="post-count"> ({{ category.num_posts }})</span></a>
                            </li>
                            {% empty %}
                            No category!
                            {% endfor %}
                        </ul>
                    </div>

                    <div class="widget widget-tag-cloud">
                        <h3 class="widget-title">Tags</h3>
                        {% get_tags as tag_list %}
                        <ul>
                            {% for tag in tag_list %}
                            <li>
                                <a href="{% url 'myblog:tag' tag.pk %}">{{ tag.name }}</a>
                            </li>
                            {% empty %}
                            No tag!
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="rss">
                        <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span>Subscription</a>
                    </div>
                    <div class="widget widget-follow-me">
                        <h3 class="widget-title"><a href="{% url 'about' %}">Follow me</a></h3>
                        <ul class="social" style="float: left;">
                            <li class="email" title="yangjufo@gmail.com"><a href="mailto:yangjufo@gmail.com" target="_top"><span class="ion-email"></span></a></li>
                            <li class="github" title="https://github.com/yangjufo"><a href="https://github.com/yangjufo"><span class="ion-social-github"></span></a></li>
                            <li class="linkedin" title="https://www.linkedin.com/in/jianyang995"><a href="https://www.linkedin.com/in/jianyang995/"><span class="ion-social-linkedin"></span></a></li>
                            <li class="facebook" title="https://www.facebook.com/yangjufo"><a href="https://www.facebook.com/yangjufo"><span class="ion-social-facebook"></span></a></li>
                        </ul>
                    </div>
                </aside>
            </div>
        </div>
    </div>
{% endblock main-body %}

templates/myblog/detail.html
{% extends 'myblog/base.html' %}
{% block title %}
{{ post.title }}
{% endblock title%}
{% block main %}
<article class="post post-{{ post.pk }}">
    <header class="entry-header">
        <h1 class="entry-title">{{ post.title }}</h1>
        <div class="entry-meta">
            <span class="post-category"><a href="{% url 'myblog:category' post.category.pk %}">{{ post.category.name }}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
            <!--<span class="post-author"><a href="#">追梦人物</a></span>-->
            <span class="views-count"><a href="#">{{ post.views }} Read</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        <div class="widget-tag-cloud">
            <ul>
                {% for tag in post.tags.all %}
                <li><a href="{% url 'myblog:tag' tag.pk %}">{{ tag.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        {{ post.body|safe }}
    </div>
</article>
{% endblock main %}
{% block toc %}
<div class="widget widget-content">
    <h3 class="widget-title">Catalog</h3>
    {{ post.toc|safe }}
</div>
{% endblock toc %}

templates/myblog/index.html
{% extends 'myblog/base.html' %}
{% block title %}
{{ title }}
{% endblock title%}
{% block main %}
{% for post in post_list %}
<article class="post post-{{ post.pk }}">
    <header class="entry-header">
        <h1 class="entry-title">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h1>
        <div class="entry-meta">
            <span class="post-category"><a href="{% url 'myblog:category' post.category.pk %}">{{ post.category }}</a></span>
            <span class="post-date"><a
                    href="{% url 'myblog:archives' post.created_time.year post.created_time.month %}"><time
                        class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
            <!--<span class="post-author"><a href="#"></a></span>-->
            <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} Read</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        <p>{{ post.excerpt }}</p>
        <div class="read-more cl-effect-14">
            <a href="{{ post.get_absolute_url }}" class="more-link">Read more <span class="meta-nav">→</span></a>
        </div>
    </div>
</article>
{% empty %}
<div class="no-post">No posted articles!</div>
{% endfor %}
{% if is_paginated %}
<div class="pagination">
    {% if first %}
    <a href="?page=1">1</a>
    {% endif %}
    {% if left %}
    {% if left_has_more %}
    <span>...</span>
    {% endif %}
    {% for i in left %}
    <a href="?page={{ i }}">{{ i }}</a>
    {% endfor %}
    {% endif %}
    <a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>
    {% if right %}
    {% for i in right %}
    <a href="?page={{ i }}">{{ i }}</a>
    {% endfor %}
    {% if right_has_more %}
    <span>...</span>
    {% endif %}
    {% endif %}
    {% if last %}
    <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
    {% endif %}
</div>
{% endif %}
{% endblock main %}