myblog/urls.py
from django.urls import path
from . import views

app_name = 'myblog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post/P<int:pk>', views.PostDetailView.as_view(), name='detail'),
    path('archives/<int:year>/<int:month>', views.ArchivesView.as_view(), name='archives'),
    path('category/C<int:pk>', views.CategoryView.as_view(), name='category'),
    path('tag/T<int:pk>', views.TagView.as_view(), name='tag'),    
]

myprojects/urls.py
from django.urls import path
from . import views

app_name = 'myprojects'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('project/P<int:pk>', views.ProjectDetailView.as_view(), name='detail'),
    path('archives/<int:year>', views.ArchivesView.as_view(), name='archives'),
    path('category/C<int:pk>', views.CategoryView.as_view(), name='category'),
    path('tag/T<int:pk>', views.TagView.as_view(), name='tag'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from myblog.feeds import AllPostRssFeed
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('all/rss/', AllPostRssFeed(), name='rss'),
    path('search/', include('haystack.urls')),
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
    path('projects/', include("myprojects.urls")),
    path('blog/', include('myblog.urls')),
    path('android_browser/', views.android_browser),
]

myprojects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.html import strip_tags
import markdown


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Project(models.Model):
    title = models.CharField(max_length=70)
    body = models.TextField()
    image = models.URLField(default="https://www.jianyang995.com/static/img/profile.jpg")
    position = models.IntegerField(default=0)
    source = models.URLField(blank=True)
    demo = models.URLField(blank=True)
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    excerpt = models.CharField(max_length=200, blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('myprojects:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['position', '-created_time']

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            self.excerpt = strip_tags(md.convert(self.body))[:54]
        super(Project, self).save(*args, **kwargs)

myprojects/views.py
import markdown
from django.shortcuts import get_object_or_404
from django.utils.text import slugify
from django.views.generic import ListView, DetailView
from markdown.extensions.toc import TocExtension

from .models import Project, Category, Tag

MONTH_NAME_MAP = {
    1: 'Jan',
    2: 'Feb',
    3: 'Mar',
    4: 'Apr',
    5: 'May',
    6: 'June',
    7: 'July',
    8: 'Aug',
    9: 'Sep',
    10: 'Oct',
    11: 'Nov',
    12: 'Dec'
}


class ProjectDetailView(DetailView):
    model = Project
    template_name = 'myprojects/detail.html'
    context_object_name = 'project'
    queryset = Project.objects.all()

    def get(self, request, *args, **kwargs):
        response = super(ProjectDetailView, self).get(request, *args, **kwargs)
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        post = super(ProjectDetailView, self).get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify=slugify)
        ])
        post.body = md.convert(post.body)
        post.toc = md.toc
        return post


class IndexView(ListView):
    model = Project
    template_name = 'myprojects/index.html'
    context_object_name = 'project_list'
    paginate_by = 4
    title = 'Projects | Jian Yang'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')
        pagination_data = self.pagination_data(paginator, page, is_paginated)
        context.update(pagination_data)
        context.update({
            'title': self.title,
        })
        return context

    @staticmethod
    def pagination_data(paginator, page, is_paginated):
        if not is_paginated:
            return {}

        left = []
        right = []
        left_has_more = False
        right_has_more = False
        first = False
        last = False

        page_number = page.number
        total_pages = paginator.num_pages
        page_range = paginator.page_range

        if page_number != 1:
            left = page_range[(page_number - 3)
                              if (page_number - 3) > 0 else 0:page_number - 1]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        if page_number != total_pages:
            right = page_range[page_number:page_number + 2]
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last
        }
        return data


class ArchivesView(IndexView):
    def get_queryset(self):
        year = self.kwargs.get('year')
        self.title = str(year) + ' | Jian Yang'
        return super(ArchivesView, self).get_queryset().filter(created_time__year=year)


class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        self.title = cate.name + ' | Jian Yang'
        return super(CategoryView, self).get_queryset().filter(category=cate)


class TagView(IndexView):
    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        self.title = tag.name + ' | Jian Yang'
        return super(TagView, self).get_queryset().filter(tags=tag)

templates/myprojects/base.html
<head>
    <style>
        span.highlighted {
            color: red;
        }
    </style>
</head>

{% extends 'basic/base.html' %}
{% load myprojects_tags %}
{% block title %}
    Projects | Jian Yang
{% endblock title%}
{% block main-body %}
    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-8">
                    {% block main %}
                    {% endblock main %}
                </main>
                <aside class="col-md-4">
                    {% block toc %}
                    {% endblock toc %}
                    <div class="widget widget-recent-projects">
                        <h3 class="widget-title">Latest</h3>
                        {% get_recent_projects as recent_project_list %}
                        <ul>                    
                            {% for project in recent_project_list %}
                            <li>
                                <a href="{{ project.get_absolute_url }}">{{ project.title }}</a>
                            </li>
                            {% empty %}
                            No project!
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="widget widget-archives">
                        <h3 class="widget-title">Archives</h3>
                        {% archives as date_list %}
                        <ul>
                            {% for a_date in date_list %}
                            <li>
                                <a href="{% url 'myprojects:archives' a_date.year %}">{{ a_date.year }}</a>
                            </li>
                            {% empty %}
                            No archive!
                            {% endfor %}
                        </ul>
                    </div>

                    <div class="widget widget-category">
                        <h3 class="widget-title">Categories</h3>
                        {% get_categories as category_list %}
                        <ul>
                            {% for category in category_list %}                        
                            <li>
                                <a href="{% url 'myprojects:category' category.pk %}">{{ category.name }}<span class="project-count"> ({{ category.num_projects }})</span></a>
                            </li>
                            {% empty %}
                            No category!
                            {% endfor %}
                        </ul>
                    </div>

                    <div class="widget widget-tag-cloud">
                        <h3 class="widget-title">Tags</h3>
                        {% get_tags as tag_list %}
                        <ul>
                            {% for tag in tag_list %}
                            <li>
                                <a href="{% url 'myprojects:tag' tag.pk %}">{{ tag.name }}</a>
                            </li>
                            {% empty %}
                            No tag!
                            {% endfor %}
                        </ul>
                    </div>

                    <div class="widget widget-follow-me">
                        <h3 class="widget-title"><a href="{% url 'about' %}">Follow me</a></h3>
                        <ul class="social" style="float: left;">
                            <li class="email" title="yangjufo@gmail.com"><a href="mailto:yangjufo@gmail.com" target="_top"><span class="ion-email"></span></a></li>
                            <li class="github" title="https://github.com/yangjufo"><a href="https://github.com/yangjufo"><span class="ion-social-github"></span></a></li>
                            <li class="linkedin" title="https://www.linkedin.com/in/jianyang995"><a href="https://www.linkedin.com/in/jianyang995/"><span class="ion-social-linkedin"></span></a></li>
                            <li class="facebook" title="https://www.facebook.com/yangjufo"><a href="https://www.facebook.com/yangjufo"><span class="ion-social-facebook"></span></a></li>
                        </ul>
                    </div>
                </aside>
            </div>
        </div>
    </div>
{% endblock main-body %}

templates/myprojects/detail.html
<head>
    <style>
        .source-code,
        .demo-link {
            text-decoration: underline;
        }
    </style>
</head>
{% extends 'myprojects/base.html' %}
{% block title %}
{{ project.title }}
{% endblock title %}
{% block main %}
<article class="project project-{{ project.pk }}">
    <header class="entry-header">
        <h1 class="entry-title">{{ project.title }}</h1>
        <div class="entry-meta">
            <span class="project-category"><a href="{% url 'myprojects:category' project.category.pk %}">{{ project.category.name }}</a></span>
            <span class="project-date"><a href="{% url 'myprojects:archives' project.created_time.year %}"><time
                        class="entry-date" datetime="{{ project.created_time }}">{{ project.created_time|date:'F' }}, {{ project.created_time.year }}, </time></a></span>
            <!--<span class="project-author"><a href="#">Jian Yang</a></span>-->
            <span class="views-count"><a href="#">{{ project.views }} Read</a></span>
            <br>
            <span><a class="source-code" href="{{ project.source }}">Source Code</a></span>
            <span style="padding-left: 20px"><a class="demo-link" href={{ project.demo }}>Demo Link</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        <div class="widget-tag-cloud">
            <ul>
                {% for tag in project.tags.all %}
                <li><a href="{% url 'myprojects:tag' tag.pk %}">{{ tag.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        {{ project.body|safe }}
    </div>
</article>
{% endblock main %}
{% block toc %}
<div class="widget widget-content">
    <h3 class="widget-title">Catalog</h3>
    {{ project.toc|safe }}
</div>
{% endblock toc %}

templates/myprojects/index.html
{% extends 'myprojects/base.html' %}
{% load static %}
{% block title %}
{{ title }}
{% endblock title %}
{% block style %}
<style>
    .project-row {
        margin: 8px -16px;
    }

    /* Add padding BETWEEN each column (if you want) */
    .project-row,
    .project-row>.project-column {
        padding: 8px;
    }

    /* Create four equal columns that floats next to each other */
    .project-column {
        float: left;
        margin-bottom: 5%;
        width: 45%;
    }

    /* Clear floats after rows */
    .project-row:after {
        content: "";
        display: table;
        clear: both;
    }

    /* Content */
    .project-content {
        background-color: white;
        padding: 10px;
    }

    .source-code,
    .demo-link {
        text-decoration: underline;
    }

    /* Responsive layout - makes a two column-layout instead of four columns */
    @media screen and (max-width: 900px) {
        .project-column {
            width: 50%;
        }
    }

    /* Responsive layout - makes the two columns stack on top of each other instead of next to each other */
    @media screen and (max-width: 600px) {
        .project-column {
            width: 100%;
        }
    }
</style>
{% endblock style %}
{% block main %}
<div class="project-row">
    {% for project in project_list %}
    <div class="project-column">
        <div class="project-content">
            <a href="{{ project.get_absolute_url }}"><img src="{{ project.image }}" alt="Cover Image"
                    style="width:400px; height: 200px"></a>
            <h3 class="entry-title" style="margin-bottom: 10px; font-size: 1.4em">
                <a href="{{ project.get_absolute_url }}">{{ project.title }}</a>
            </h3>
            <div class="entry-meta">
                <span class="project-category"><a href="{% url 'myprojects:category' project.category.pk %}">{{ project.category }}</a></span>
                <span class="project-date"><a href="{% url 'myprojects:archives' project.created_time.year %}"><time
                            class="entry-date" datetime="{{ project.created_time }}">{{ project.created_time.year }}</time></a></span>
                <!--<span class="project-author"><a href="#"></a></span>-->
                <span class="views-count"><a href="{{ project.get_absolute_url }}">{{ project.views }} Read</a></span>
                <br>
                <span><a class="source-code" href="{{ project.source }}">Source Code</a></span>
                <span style="padding-left: 20px"><a class="demo-link" href={{ project.demo }}>Demo Link</a></span>
            </div>
        </div>
    </div>
    {% empty %}
    <div class="no-project">No projects!</div>
    {% endfor %}
</div>
{% if is_paginated %}
<div class="pagination">
    {% if first %}
    <a href="?page=1">1</a>
    {% endif %}
    {% if left %}
    {% if left_has_more %}
    <span>...</span>
    {% endif %}
    {% for i in left %}
    <a href="?page={{ i }}">{{ i }}</a>
    {% endfor %}
    {% endif %}
    <a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>
    {% if right %}
    {% for i in right %}
    <a href="?page={{ i }}">{{ i }}</a>
    {% endfor %}
    {% if right_has_more %}
    <span>...</span>
    {% endif %}
    {% endif %}
    {% if last %}
    <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
    {% endif %}
</div>
{% endif %}
{% endblock main %}