myblog/urls.py
from django.urls import path
from . import views

app_name = 'myblog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post/P<int:pk>', views.PostDetailView.as_view(), name='detail'),
    path('archives/<int:year>/<int:month>', views.ArchivesView.as_view(), name='archives'),
    path('category/C<int:pk>', views.CategoryView.as_view(), name='category'),
    path('tag/T<int:pk>', views.TagView.as_view(), name='tag'),    
]

myprojects/urls.py
from django.urls import path
from . import views

app_name = 'myprojects'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('project/P<int:pk>', views.ProjectDetailView.as_view(), name='detail'),
    path('archives/<int:year>', views.ArchivesView.as_view(), name='archives'),
    path('category/C<int:pk>', views.CategoryView.as_view(), name='category'),
    path('tag/T<int:pk>', views.TagView.as_view(), name='tag'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from myblog.feeds import AllPostRssFeed
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('all/rss/', AllPostRssFeed(), name='rss'),
    path('search/', include('haystack.urls')),
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
    path('projects/', include("myprojects.urls")),
    path('blog/', include('myblog.urls')),
    path('android_browser/', views.android_browser),
]

templates/basic/about.html
<head>
	<style>
		img {
			width: 20%;
		}
	</style>
</head>
{% extends 'basic/base.html' %}
{% load static %}
{% block title %}About | Jian Yang{% endblock title%}
{% block main-body %}
	<div class="content-body">
		<div class="container">
			<div class="row">
				<main class="col-md-12">
					<h1 class="page-title">About Me</h1>
					<article class="post">
						<div class="entry-content clearfix">
							<figure class="img-responsive-center">
								<img class="img-responsive" src="{% static 'img/profile.jpg' %}" alt="Developer Image">
							</figure>
							<p>Jian is a programmer, developer and student. He currently focuses on software engineering, especially user-centric. He loves to explore new technologies and adopt them in developing.</p>
							<p>Jian is also a fan of sports, including basketball, runing, etc. He enjoys making new friends and sharing with others.</p>
							<p>For more about his experiences, please refer to his <a href="https://docs.google.com/document/d/1h1BR7kiWZKRJkI8oJBvRX2ZBZkB6M-hRixL1Wf1YszA/edit?usp=sharing" class="underline-a">Resume.</a></p>
							<div class="height-40px"></div>
							<h2 class="title text-center">Social</h2>
							<ul class="social">
								<li class="email" title="yangjufo@gmail.com"><a href="mailto:yangjufo@gmail.com" target="_top"><span class="ion-email"></span></a></li>
								<li class="github" title="https://github.com/yangjufo"><a href="https://github.com/yangjufo"><span class="ion-social-github"></span></a></li>
								<li class="linkedin" title="https://www.linkedin.com/in/jianyang995"><a href="https://www.linkedin.com/in/jianyang995/"><span class="ion-social-linkedin"></span></a></li>
								<li class="facebook" title="https://www.facebook.com/yangjufo"><a href="https://www.facebook.com/yangjufo"><span class="ion-social-facebook"></span></a></li>
							</ul>
						</div>
					</article>
				</main>
			</div>
		</div>
	</div>
{% endblock main-body %}

templates/basic/base.html
{% load static %}
<html lang="en">

<head>
    <title>{% block title %}{% endblock title%}</title>
    {% block style %}{% endblock style %}
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon/favicon.ico' %}" />

    <!-- css -->
    <link rel="stylesheet" type="text/css" href="{% static 'basic/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'myblog/css/pace.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'basic/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'myblog/css/highlights/github.css' %}">

    <!-- js -->
    <script src="{% static 'basic/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'basic/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'myblog/js/pace.min.js' %}"></script>
    <script src="{% static 'myblog/js/modernizr.custom.js' %}"></script>

</head>

<body>
    <div class="container">
        <header id="site-header">
            <div class="row">
                <div class="col-md-4 col-sm-5 col-xs-8">
                    <div class="logo">
                        <h1 class="logo-h1"><a href="{% url 'index' %}"><b>Jian</b> Yang</a></h1>
                        <h4 class="logo-h4">A man who is always on the way.</h4>
                    </div>
                </div><!-- col-md-4 -->
                <div class="col-md-8 col-sm-7 col-xs-4">
                    <nav class="main-nav" role="navigation">
                        <div class="navbar-header">
                            <button type="button" id="trigger-overlay" class="navbar-toggle">
                                <span class="ion-navicon"></span>
                            </button>
                        </div>

                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav navbar-right">
                                <li class="cl-effect-11"><a href="{% url 'index' %}" data-hover="Home">Home</a></li>
                                <li class="cl-effect-11"><a href="{% url 'myblog:index' %}" data-hover="Blog">Blog</a>
                                </li>
                                <li class="cl-effect-11"><a href="{% url 'myprojects:index' %}"
                                        data-hover="Projects">Projects</a></li>
                                <li class="cl-effect-11"><a href="{% url 'about' %}" data-hover="About">About</a></li>
                            </ul>
                            <div id="search-form-full" class="search-form-full">
                                <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                                    <input type="search" name="q" placeholder="Search" required>
                                    <button type="submit"><span class="ion-ios-search-strong"></span></button>
                                </form>
                            </div>
                        </div><!-- /.navbar-collapse -->
                    </nav>
                </div><!-- col-md-8 -->
            </div>
        </header>
    </div>
    {% block main-body %}
    {% endblock main-body %}
    <footer id="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p class="copyright">&copy; 2018-2023 Jian Yang All rights reserved </p>
                </div>
            </div>
        </div>
    </footer>

    <!-- Mobile Menu -->
    <div class="overlay overlay-hugeinc">
        <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
        <nav>
            <ul>
                <li><a href="{% url 'myprojects:index' %}" data-hover="Home">Home</a></li>
                <li><a href="{% url 'myblog:index' %}" data-hover="Blog">Blog</a></li>
                <li><a href="{% url 'myprojects:index' %}" data-hover="Projects">Projects</a></li>
                <li><a href="{% url 'about' %}" data-hover="About">About</a></li>
            </ul>
            <div id="header-search-box">
                <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                <div id="search-form" class="search-form">
                    <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                        <input type="search" name="q" placeholder="Search" required>
                        <button type="submit"><span class="ion-ios-search-strong"></span></button>
                    </form>
                </div>
            </div>
        </nav>
    </div>

    <script src="{% static 'myblog/js/script.js' %}"></script>

</body>

</html>

templates/basic/index.html
{% extends 'basic/base.html' %}
{% load static %}
{% load myblog_tags %}
{% load myprojects_tags %}
{% block title %}
    Welcome | Jian Yang
{% endblock title %}
{% block style %}
    <link rel="stylesheet" href="{% static 'basic/css/mycalendar.css' %}">
    <style>
        .index-row {
            margin: 8px -16px;
        }

        /* Add padding BETWEEN each column (if you want) */
        .index-row,
        .index-row > .index-column {
            padding: 8px;
        }

        /* Create four equal columns that floats next to each other */
        .index-column {
            float: left;
            margin-bottom: 5%;
            width: 45%;
        }

        /* Clear floats after rows */
        .index-row:after {
            content: "";
            display: table;
            clear: both;
        }

        /* Content */
        .index-content {
            background-color: white;
        }

        /* Responsive layout - makes a two column-layout instead of four columns */
        @media screen and (max-width: 900px) {
            .index-column {
                width: 50%;
            }
        }

        /* Responsive layout - makes the two columns stack on top of each other instead of next to each other */
        @media screen and (max-width: 600px) {
            .index-column {
                width: 100%;
            }
        }

        .welcome-p {
            margin-top: 5%;
            font-size: 1.4em;
        }

        .list-li {
            font-size: 1.2em;
            margin-bottom: 1%;
        }

    </style>
{% endblock style %}
{% block main-body %}
    <div class="container">
        <div class="index-row">
            <div class="index-column">
                <section class="calendar-month" id="january">
                    <header class="calendar-header">
                        <h1 class="calendar-h1"> {{ current_date|date:'F' }} {{ current_date.year }}</h1>
                    </header>

                    <article class="calendar-article">
                        <div class="days">
                            <b>SU</b>
                            <b>MO</b>
                            <b>TU</b>
                            <b>WE</b>
                            <b>TH</b>
                            <b>FR</b>
                            <b>SA</b>
                        </div>
                        <div class="dates">
                            {% for day in day_before %}
                                <span class="disable">{{ day }}</span>
                            {% endfor %}

                            {% for day in day_month %}
                                {% if day != current_date.day %}
                                    <span>{{ day }}</span>
                                {% else %}
                                    <span class="active">{{ day }}</span>
                                {% endif %}
                            {% endfor %}

                            {% for day in day_after %}
                                <span class="disable">{{ day }}</span>
                            {% endfor %}
                        </div>
                    </article>
                </section>
            </div>
            <div class="index-column">
                <div class="index-content">
                    <h1>Welcome</h1>
                    <p align="justify" class="welcome-p">Thanks for stopping by. Hope you can
                        find resources here on creativity, innovation and fun! Use the
                        <a href="{% url 'myblog:index' %}" class="underline-a" data-hover="Blog">Blog</a>
                        <a href="{% url 'myprojects:index' %}" class="underline-a" data-hover="Projects">Projects</a>
                        links to explore.
                    <p align="justify" class="welcome-p">Here are few recent postings and
                        projects:</p>
                    {% get_recent_posts 2 as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                            <li class="list-li">
                                <a class="underline-a" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </li>
                        {% empty %}
                            No post!
                        {% endfor %}
                    </ul>
                    {% get_recent_projects 2 as recent_project_list %}
                    <ul>
                        {% for project in recent_project_list %}
                            <li class="list-li">
                                <a class="underline-a"
                                   href="{{ project.get_absolute_url }}">{{ project.title }}</a> -- {{ project.excerpt }}                                   
                            </li>
                        {% empty %}
                            No project!
                        {% endfor %}
                    </ul>
                    <div class="follow-me" style="margin-top:5%;">
                        <h3 style="margin-bottom:6%;">Follow <a href="{% url 'about' %}" class="underline-a">me</a></h3>
                        <ul class="social" style="float: left;">
                            <li class="email" title="yangjufo@gmail.com"><a href="mailto:yangjufo@gmail.com" target="_top"><span class="ion-email"></span></a></li>
                            <li class="github" title="https://github.com/yangjufo"><a href="https://github.com/yangjufo"><span class="ion-social-github"></span></a></li>
                            <li class="linkedin" title="https://www.linkedin.com/in/jianyang995"><a href="https://www.linkedin.com/in/jianyang995/"><span class="ion-social-linkedin"></span></a></li>
                            <li class="facebook" title="https://www.facebook.com/yangjufo"><a href="https://www.facebook.com/yangjufo"><span class="ion-social-facebook"></span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock main-body %}